
[[redirects]]
  from = "/api/estimate"
  to = "https://estimate-pwil4mmbgq-uc.a.run.app"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
[[redirects]]
  from = "/api/bridge"
  to = "https://bridgeandmessage-pwil4mmbgq-uc.a.run.app"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
